### ISSUE TITLE
Updating from 2.40 to 3.0.0 caused errors on older kernel

### ISSUE THREAD

**Issue by ggascoigne** [chef-cookbooks/build-essential#100]
Using a box (Centos 7.1) with kernel 3.10.0-229.el7.  The 3.10.0-229.el7 kernel-devel package is no longer available and since the newer cookbook enforces only loading the version that explicitly matches the kernel the package install fails.  The older version of the cookbook installs version 3.10.0-327.10.1.el7 instead.

I'm actually using the mysql cookbook, and this is coming in as part of its dependency chain.  Pinning to 2.4.0 unblocks me.

**Comment by mfischer-zd** [comment]
CentOS places older kernel revisions in the Vault; see https://wiki.centos.org/HowTos/I_need_the_Kernel_Source

If this recipe is going to install a matching kernel-devel, it needs to be have more advanced logic so that it may obtain it from the vault instead of trying to install it by name only via yum.

**Comment by tas50** [comment]
I'm going to pull this functionality today.  It's caused unexpected problems in a few areas including mocking using Chefspec.

**Comment by ggascoigne** [comment]
Oh and just to close the loop, I can confirm that 3.2.0 fixed my problems.  Thank you.
